name: "sharpDox"
url: "http://localhost:4000"

appversion: "0.9.8.2"
appdatede: "Januar 2014"
appdateen: "January 2014"
appdownloadurl: "https://github.com/Geaz/sharpDox/releases/download/v0.9.8.2/sharpDox.0.9.8.2.zip"