name: "sharpDox"
url: "http://localhost:4000"

appversion: "0.9.8.3"
appdatede: "Februar 2014"
appdateen: "February 2014"
appdownloadurl: "https://github.com/Geaz/sharpDox/releases/download/v0.9.8.3/sharpDox.0.9.8.3.zip"